package com.sysagent.sysagent_backend.model.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The response from the AI Engine after analyzing an intent.
 * Includes the generated script, an explanation, and the task ID.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AgentIntentResponseDto {
    
    /**
     * Unique identifier for the created task, used to track status.
     */
    private String taskId;
    
    /**
     * The shell script or command generated by the AI model.
     */
    private String script;
    
    /**
     * A human-readable explanation of what the script does (e.g., "This command removes all log files larger than 10MB").
     */
    private String explanation;
    
    /**
     * Confidence score of the AI model for this generation (0.0 to 1.0).
     */
    private Double confidenceScore;

    /**
     * Number of tasks still queued after this response.
     * Used by frontend to decide whether to trigger auto-resume after script approval.
     */
    private int pendingCount;
}
