package com.sysagent.sysagent_backend.adapter;

import com.sysagent.sysagent_backend.model.dto.AgentIntentResponseDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Slf4j
@Component
public class MockAiAgentAdapterImpl implements AiAgentAdapter {

    @Override
    public AgentIntentResponseDto analyzeIntent(String taskId, String intent) {
        log.info("Mock AI Adapter analyzing intent for Task ID: {}", taskId);
        
        // This simulates a slight delay that a real AI request would take
        try {
            Thread.sleep(1500);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        // Mock response generation based on the intent
        String simulatedScript = generateSimulatedScript(intent);
        
        return AgentIntentResponseDto.builder()
                .taskId(taskId)
                .script(simulatedScript)
                .explanation("This is a dry-run script generated by the SysAgent AI Mock Adapter. Please review carefully before execution.")
                .build();
    }
    
    private String generateSimulatedScript(String intent) {
        String lowerIntent = intent.toLowerCase();
        
        if (lowerIntent.contains("docker")) {
            return "docker ps -a\ndocker system prune -f";
        } else if (lowerIntent.contains("temp") || lowerIntent.contains("clean")) {
            return "$tempPath = [System.IO.Path]::GetTempPath()\nRemove-Item \"$tempPath\\*\" -Recurse -Force -ErrorAction SilentlyContinue";
        } else if (lowerIntent.contains("cpu") || lowerIntent.contains("ram") || lowerIntent.contains("memory")) {
            return "Get-Process | Sort-Object CPU -Descending | Select-Object -First 10";
        } else {
            return "Write-Host \"Command not recognized by mock agent. Intent: " + intent + "\"";
        }
    }
}
